project:
  type: website

website:
  title: "Women in Logic"
  favicon: assets/favicon.png

  navbar:
    search: true
    logo: assets/logo_white.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: workshops/index.qmd
        text: Workshops
      - href: wil-online/index.qmd
        text: WiL Online
      - href: data/index.qmd
        text: Data
      - href: https://womeninlogic.github.io/RecordedTalks/
        text: Recorded Talks
      - href: social/index.qmd
        text: Social
    tools:
      - icon: twitter
        href: https://twitter.com/womeninlogic1
      - icon: facebook
        href: https://www.facebook.com/groups/WomenInLogic
      - icon: pen
        href: https://blog.womeninlogic.org
      - icon: camera-reels
        href: https://womeninlogic.github.io/RecordedTalks/

  sidebar:
    - title: "Workshops"
      style: docked
      contents:
        - workshops/index.qmd
        - text: "---"
        - section: "2026"
          contents:
          - href: workshops/2026/index.qmd
            text: Home
          - href: workshops/2026/committees/index.qmd
            text: Committees
          - href: workshops/2026/program/index.qmd
            text: Program
          - href: workshops/2026/call-for-papers/index.qmd
            text: Call for papers
          - href: workshops/2026/speakers/index.qmd
            text: Speakers
          - href: workshops/2026/photos/index.qmd
            text: Photos
          - href: workshops/2026/venue/index.qmd
            text: Venue

  back-to-top-navigation: false
  page-footer:
    center: |
      Contact us by email: [<i class="bi bi-envelope-at"></i> `contact@womeninlogic.org`](mailto:contact@womeninlogic.org)

format:
  html:
    theme: pulse
    css: assets/styles.css
    toc: false
    anchor-sections: false