project:
  type: website

website:
  title: "Women in Logic"
  favicon: assets/favicon.png

  navbar:
    search: true
    logo: assets/logo_white.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - href: workshops/index.qmd
        text: Workshops
      - href: wil-online/index.qmd
        text: WiL Online
      - href: data/index.qmd
        text: Data
      - href: https://womeninlogic.github.io/RecordedTalks/
        text: Recorded Talks
      - href: social/index.qmd
        text: Social
    tools:
      - icon: twitter
        href: https://twitter.com/womeninlogic1
      - icon: facebook
        href: https://www.facebook.com/groups/WomenInLogic
      - icon: pen
        href: https://blog.womeninlogic.org
      - icon: camera-reels
        href: https://womeninlogic.github.io/RecordedTalks/

  sidebar:
    - title: "Workshops"
      style: docked
      collapse-level: 1
      contents:
        - workshops/index.qmd
        - text: "---"
        - auto: "workshops/2026"
        - text: "---"
        - auto: "workshops/2025/"
        - auto: "workshops/2024/"
        - auto: "workshops/2023/"
        - auto: "workshops/2022/"
        - auto: "workshops/2021/"
        - auto: "workshops/2020/"
        - auto: "workshops/2019/"
        - auto: "workshops/2018/"
        - auto: "workshops/2017/"

  back-to-top-navigation: false
  page-footer:
    center: |
      Contact us by email: [<i class="bi bi-envelope-at"></i> `contact@womeninlogic.org`](mailto:contact@womeninlogic.org)

format:
  html:
    theme: pulse
    css: assets/styles.css
    toc: false
    anchor-sections: false